// packages/core/src/internal/growing-entry/growing-entry.tsx
import * as React from "react";

import { GrowingEntryStyle, ShadowBox, InputBox } from "./growing-entry-style";
import { assert } from "../../common/support";
import type { SelectionRange } from "../data-grid/data-grid-types";

interface Props
    extends React.DetailedHTMLProps<React.TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement> {
    readonly placeholder?: string;
    readonly highlight: boolean;
    readonly altNewline?: boolean;
    readonly validatedSelection?: SelectionRange;
}

let globalInputID = 0;

/** @category Renderers */
export const GrowingEntry: React.FunctionComponent<Props> = (props: Props) => {
    const { placeholder, value, onKeyDown, highlight, altNewline, validatedSelection, ...rest } = props;
    const { onChange, className } = rest;

    const inputRef = React.useRef<HTMLTextAreaElement | null>(null);

    const useText = value ?? ";

    assert(onChange !== undefined, "GrowingEntry must be a controlled input area");

    // 10 million id's aught to be enough for anybody
    const [inputID] = React.useState(() => "input-box-" + (globalInputID = (globalInputID + 1) % 10_000_000));

    React.useEffect(() => {
        const ta = inputRef.current;
        if (ta === null) return;

        if (ta.disabled) return;
        const length = useText.toString().length;
        ta.focus();
        ta.setSelectionRange(highlight ? 0 : length, length);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    React.useLayoutEffect(() => {
        if (validatedSelection !== undefined) {
            const range = typeof validatedSelection === "number" ? [validatedSelection, null] : validatedSelection;
            inputRef.current?.setSelectionRange(range[0], range[1]);
        }
    }, [validatedSelection]);

    const onKeyDownInner = React.useCallback<NonNullable<typeof onKeyDown>>(
        e => {
            if (e.key === "Enter" && e.shiftKey && altNewline === true) {
                return;
            }
            onKeyDown?.(e);
        },
        [altNewline, onKeyDown]
    );

    return (
        <GrowingEntryStyle className="gdg-growing-entry">
            <ShadowBox className={className}>{useText + "\n"}</ShadowBox>
            <InputBox
                {...rest}
                className={(className ?? "") + " gdg-input"}
                id={inputID}
                ref={inputRef}
                onKeyDown={onKeyDownInner}
                value={useText}
                placeholder={placeholder}
                dir="auto"
            />
        </GrowingEntryStyle>
    );
};

// packages/vue-core/src/internal/growing-entry/growing-entry.vue
<template>
  <GrowingEntryStyle class="gdg-growing-entry">
    <ShadowBox :class="className">{{ useText + '\n' }}</ShadowBox>
    <InputBox
      :class="(className ?? '') + ' gdg-input'"
      :id="inputID"
      ref="inputRef"
      :value="useText"
      :placeholder="placeholder"
      dir="auto"
      @keydown="onKeyDownInner"
      @input="handleInput"
      v-bind="restProps"
    />
  </GrowingEntryStyle>
</template>

<script setup lang="ts">
import { ref, onMounted, onUpdated, computed } from 'vue';
import { GrowingEntryStyle, ShadowBox, InputBox } from './growing-entry-style.js';
import { assert } from '../../common/support.js';
import type { SelectionRange } from '../data-grid/data-grid-types.js';

interface Props {
  placeholder?: string;
  highlight: boolean;
  altNewline?: boolean;
  validatedSelection?: SelectionRange;
  value?: string;
  onChange?: (event: Event) => void;
  onKeyDown?: (event: KeyboardEvent) => void;
  className?: string;
  disabled?: boolean;
  [key: string]: any;
}

const props = defineProps<Props>();

const inputRef = ref<HTMLTextAreaElement | null>(null);

let globalInputID = 0;
const inputID = ref(`input-box-${(globalInputID = (globalInputID + 1) % 10_000_000)}`);

const useText = computed(() => props.value ?? "");

assert(props.onChange !== undefined, "GrowingEntry must be a controlled input area");

onMounted(() => {
  const ta = inputRef.value;
  if (ta === null) return;

  if (ta.disabled) return;
  const length = useText.value.toString().length;
  ta.focus();
  ta.setSelectionRange(props.highlight ? 0 : length, length);
});

onUpdated(() => {
  if (props.validatedSelection !== undefined) {
    const range = typeof props.validatedSelection === "number" ? [props.validatedSelection, null] : props.validatedSelection;
    inputRef.value?.setSelectionRange(range[0], range[1]);
  }
});

const onKeyDownInner = (e: KeyboardEvent) => {
  if (e.key === "Enter" && e.shiftKey && props.altNewline === true) {
    return;
  }
  props.onKeyDown?.(e);
};

const handleInput = (e: Event) => {
  props.onChange?.(e);
};

// Extract rest props
const restProps = computed(() => {
  const { placeholder, value, onKeyDown, highlight, altNewline, validatedSelection, onChange, className, ...rest } = props;
  return rest;
});
</script>
