// packages/vue-core/src/cells/uri-cell.vue
<template>
  <div class="uri-cell">
    <!-- Vue版本的URI单元格渲染器 -->
  </div>
</template>

<script setup lang="ts">
import { ref, computed, h, defineComponent } from 'vue';
import { drawTextCellExternal } from '../internal/data-grid/render/data-grid-lib.js';
import { GridCellKind, type UriCell } from '../internal/data-grid/data-grid-types.js';
import type { InternalCellRenderer } from './cell-types.js';

// Vue版本的URI编辑器组件
const UriOverlayEditor = defineComponent({
  props: {
    highlight: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    value: {
      type: String,
      default: ''
    },
    forceEditMode: {
      type: Boolean,
      default: false
    },
    validatedSelection: {
      type: Object,
      default: undefined
    }
  },
  emits: ['change'],
  setup(props, { emit }) {
    const inputRef = ref<HTMLInputElement | null>(null);
    
    const handleChange = (event: Event) => {
      const target = event.target as HTMLInputElement;
      emit('change', {
        target: {
          value: target.value
        }
      });
    };
    
    return () => h('input', {
      ref: inputRef,
      type: 'text',
      class: {
        'uri-editor': true,
        'highlight': props.highlight,
        'disabled': props.disabled
      },
      value: props.value,
      disabled: props.disabled,
      autofocus: props.forceEditMode,
      onInput: handleChange,
      onChange: handleChange
    });
  }
});

// Vue版本的URI单元格渲染器
export const uriCellRenderer: InternalCellRenderer<any> = {
    getAccessibilityString: c => c.data?.toString() ?? "",
    kind: GridCellKind.Uri,
    needsHover: true,
    needsHoverPosition: false,
    useLabel: true,
    drawPrep: undefined,
    draw: a => {
        const { cell, theme, rect, ctx, highlighted, hoverAmount } = a;
        const { displayData, data, hoverEffect } = cell;
        const display = displayData ?? data;
        const drawUnderline = cell.hoverEffect === true || hoverEffect === true;
        const color = cell.onClickUri !== undefined ? theme.linkColor : theme.textDark;
        const x = rect.x + theme.cellHorizontalPadding;
        const y = rect.y + theme.cellVerticalPadding;
        const w = rect.width - theme.cellHorizontalPadding * 2;
        const h = rect.height - theme.cellVerticalPadding * 2;
        const underlineHeight = Math.min(2, Math.ceil(h / 12));

        if (highlighted || (hoverEffect === true && hoverAmount > 0)) {
            ctx.fillStyle = drawUnderline ? theme.bgBubble : theme.bgSearchResult;
            let radius = theme.roundingRadius ?? 4;
            if (drawUnderline) {
                radius = Math.min(radius, underlineHeight);
            }
            ctx.beginPath();
            ctx.roundRect(x, y + h - underlineHeight - radius, w, underlineHeight + radius, radius);
            ctx.fill();
        }

        ctx.save();
        ctx.beginPath();
        ctx.rect(x, y, w, h);
        ctx.clip();

        drawTextCellExternal(a, display, cell.contentAlign);

        if (drawUnderline) {
            const metrics = ctx.measureText(display);
            const textWidth = metrics.width;
            const textHeight = metrics.actualBoundingBoxAscent + metrics.actualBoundingBoxDescent;
            const textX = rect.x + theme.cellHorizontalPadding;
            const textY = rect.y + rect.height / 2 - textHeight / 2;

            ctx.beginPath();
            ctx.strokeStyle = color;
            ctx.lineWidth = underlineHeight;
            ctx.moveTo(textX, textY + textHeight + underlineHeight);
            ctx.lineTo(textX + textWidth, textY + textHeight + underlineHeight);
            ctx.stroke();
        }

        ctx.restore();
    },
    measure: (ctx, cell, theme) => {
        const text = cell.displayData ?? cell.data;
        return ctx.measureText(text).width + theme.cellHorizontalPadding * 2;
    },
    onDelete: c => ({
        ...c,
        data: "",
    }),
    provideEditor: () => ({
        editor: (p: any) => {
            const { onChange, value, forceEditMode, validatedSelection } = p;
            return h(UriOverlayEditor, {
                highlight: p.isHighlighted,
                disabled: value.readonly === true,
                value: value.data,
                preview: value.displayData ?? value.data,
                forceEditMode,
                validatedSelection,
                onChange
            });
        }
    }),
    onClick: e => {
        const { cell, posX, posY, bounds, theme } = e;
        if (cell.onClickUri !== undefined) {
            const { x, y, width, height } = bounds;
            const padding = theme.cellHorizontalPadding;
            const text = cell.displayData ?? cell.data;
            // 由于Vue版本中没有ctx，我们使用一个简化的检测方式
            const metrics = { width: text.length * 8, height: 16 }; // 简化计算，实际应该使用canvas
            const textWidth = metrics.width;
            const textHeight = metrics.height;
            const textX = x + padding;
            const textY = y + height / 2 - textHeight / 2;

            if (
                posX >= textX &&
                posX <= textX + textWidth &&
                posY >= textY &&
                posY <= textY + textHeight
            ) {
                cell.onClickUri({
                    ...e,
                    preventDefault: () => {
                        e.preventDefault();
                    },
                });
            }
        }
        return undefined;
    },
    onPaste: (toPaste, cell, details) =>
        toPaste === cell.data
            ? undefined
            : { ...cell, data: toPaste, displayData: details.formattedString ?? cell.displayData },
};
</script>

<style scoped>
.uri-cell {
  width: 100%;
  height: 100%;
}

.uri-editor {
  width: 100%;
  height: 100%;
  border: none;
  background: transparent;
  font-family: inherit;
  font-size: inherit;
  text-align: inherit;
  outline: none;
}

.uri-editor.highlight {
  background-color: rgba(79, 93, 255, 0.1);
}

.uri-editor:disabled {
  cursor: not-allowed;
  opacity: 0.7;
}
</style>

// packages/core/src/cells/uri-cell.tsx
/* eslint-disable react/display-name */
import * as React from "react";
import UriOverlayEditor from "../internal/data-grid-overlay-editor/private/uri-overlay-editor.js";
import {
    drawTextCell,
    getMeasuredTextCache,
    getMiddleCenterBias,
    measureTextCached,
    prepTextCell,
} from "../internal/data-grid/render/data-grid-lib.js";
import {
    GridCellKind,
    type BaseGridCell,
    type Rectangle,
    type UriCell,
} from "../internal/data-grid/data-grid-types.js";
import type { InternalCellRenderer } from "./cell-types.js";
import type { FullTheme } from "../common/styles.js";
import { pointInRect } from "@glideapps/glide-data-grid-shared/geometry";

function getTextRect(
    metrics: TextMetrics,
    rect: Rectangle,
    theme: FullTheme,
    contentAlign: BaseGridCell["contentAlign"]
): Rectangle {
    let x = theme.cellHorizontalPadding;
    const y = rect.height / 2 - metrics.actualBoundingBoxAscent / 2;
    const width = metrics.width;
    const height = metrics.actualBoundingBoxAscent;

    if (contentAlign === "right") {
        x = rect.width - width - theme.cellHorizontalPadding;
    } else if (contentAlign === "center") {
        x = rect.width / 2 - width / 2;
    }

    return { x, y, width, height };
}

function isOverLinkText(e: {
    readonly cell: UriCell;
    readonly posX: number;
    readonly posY: number;
    readonly bounds: Rectangle;
    readonly theme: FullTheme;
}): boolean {
    const { cell, bounds, posX, posY, theme } = e;
    const txt = cell.displayData ?? cell.data;
    if (cell.hoverEffect !== true || cell.onClickUri === undefined) return false;

    const m = getMeasuredTextCache(txt, theme.baseFontFull);
    if (m === undefined) return false;
    const textRect = getTextRect(m, bounds, theme, cell.contentAlign);
    return pointInRect(
        {
            x: textRect.x - 4,
            y: textRect.y - 4,
            width: textRect.width + 8,
            height: textRect.height + 8,
        },
        posX,
        posY
    );
}

export const uriCellRenderer: InternalCellRenderer<UriCell> = {
    getAccessibilityString: c => c.data?.toString() ?? "",
    kind: GridCellKind.Uri,
    needsHover: uriCell => uriCell.hoverEffect === true,
    needsHoverPosition: true,
    useLabel: true,
    drawPrep: prepTextCell,
    draw: a => {
        const { cell, theme, overrideCursor, hoverX, hoverY, rect, ctx } = a;
        const txt = cell.displayData ?? cell.data;
        const isLinky = cell.hoverEffect === true;
        if (overrideCursor !== undefined && isLinky && hoverX !== undefined && hoverY !== undefined) {
            const m = measureTextCached(txt, ctx, theme.baseFontFull);
            const textRect = getTextRect(m, rect, theme, cell.contentAlign);

            const { x, y, width: w, height: h } = textRect;

            // check if hoverX and hoverY inside the box
            if (hoverX >= x - 4 && hoverX <= x - 4 + w + 8 && hoverY >= y - 4 && hoverY <= y - 4 + h + 8) {
                const middleCenterBias = getMiddleCenterBias(ctx, theme.baseFontFull);
                overrideCursor("pointer");
                const underlineOffset = 5;
                const drawY = y - middleCenterBias;

                ctx.beginPath();
                ctx.moveTo(rect.x + x, Math.floor(rect.y + drawY + h + underlineOffset) + 0.5);
                ctx.lineTo(rect.x + x + w, Math.floor(rect.y + drawY + h + underlineOffset) + 0.5);

                ctx.strokeStyle = theme.linkColor;
                ctx.stroke();

                ctx.save();
                ctx.fillStyle = a.cellFillColor;
                drawTextCell({ ...a, rect: { ...rect, x: rect.x - 1 } }, txt, cell.contentAlign);
                drawTextCell({ ...a, rect: { ...rect, x: rect.x - 2 } }, txt, cell.contentAlign);
                drawTextCell({ ...a, rect: { ...rect, x: rect.x + 1 } }, txt, cell.contentAlign);
                drawTextCell({ ...a, rect: { ...rect, x: rect.x + 2 } }, txt, cell.contentAlign);
                ctx.restore();
            }
        }

        ctx.fillStyle = isLinky ? theme.linkColor : theme.textDark;
        drawTextCell(a, txt, cell.contentAlign);
    },
    onSelect: e => {
        if (isOverLinkText(e)) {
            e.preventDefault();
        }
    },
    onClick: a => {
        const { cell } = a;
        const didClick = isOverLinkText(a);
        if (didClick) {
            cell.onClickUri?.(a);
        }
        return undefined;
    },
    measure: (ctx, cell, theme) =>
        ctx.measureText(cell.displayData ?? cell.data).width + theme.cellHorizontalPadding * 2,
    onDelete: c => ({
        ...c,
        data: "",
    }),
    provideEditor: cell => p => {
        const { onChange, value, forceEditMode, validatedSelection } = p;
        return (
            <UriOverlayEditor
                forceEditMode={
                    value.readonly !== true &&
                    (forceEditMode || (cell.hoverEffect === true && cell.onClickUri !== undefined))
                }
                uri={value.data}
                preview={value.displayData ?? value.data}
                validatedSelection={validatedSelection}
                readonly={value.readonly === true}
                onChange={e =>
                    onChange({
                        ...value,
                        data: e.target.value,
                    })
                }
            />
        );
    },
    onPaste: (toPaste, cell, details) =>
        toPaste === cell.data
            ? undefined
            : { ...cell, data: toPaste, displayData: details.formattedString ?? cell.displayData },
};
