// packages/vue-core/src/internal/data-grid-overlay-editor/private/uri-overlay-editor.vue
<template>
  <GrowingEntry
    v-if="editMode"
    :validatedSelection="validatedSelection"
    :highlight="true"
    autoFocus
    :value="uri"
    @change="onChange"
  />
  <UriOverlayEditorStyle v-else>
    <a class="gdg-link-area" :href="uri" target="_blank" rel="noopener noreferrer">
      {{ preview }}
    </a>
    <div
      v-if="!readonly"
      class="gdg-edit-icon"
      @click="onEditClick"
    >
      <EditPencil />
    </div>
    <textarea class="gdg-input" autofocus />
  </UriOverlayEditorStyle>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { EditPencil } from '../../../common/utils.js';
import GrowingEntry from '../../growing-entry/growing-entry.vue';
import UriOverlayEditorStyle from './uri-overlay-editor-style.vue';
import type { SelectionRange } from '../../data-grid/data-grid-types.js';

interface Props {
  readonly uri: string;
  readonly onChange: (ev: Event) => void;
  readonly forceEditMode: boolean;
  readonly readonly: boolean;
  readonly preview: string;
  readonly validatedSelection?: SelectionRange;
}

const props = defineProps<Props>();

const editMode = ref(!props.readonly && (props.uri === "" || props.forceEditMode));

const onEditClick = () => {
  editMode.value = true;
};
</script>

// packages/core/src/internal/data-grid-overlay-editor/private/uri-overlay-editor.tsx
import { EditPencil } from "../../../common/utils";
import * as React from "react";
import { GrowingEntry } from "../../growing-entry/growing-entry";
import { UriOverlayEditorStyle } from "./uri-overlay-editor-style";
import type { SelectionRange } from "../../data-grid/data-grid-types";

interface Props {
    readonly uri: string;
    readonly onChange: (ev: React.ChangeEvent<HTMLTextAreaElement>) => void;
    readonly forceEditMode: boolean;
    readonly readonly: boolean;
    readonly preview: string;
    readonly validatedSelection?: SelectionRange;
}

const UriOverlayEditor: React.FunctionComponent<Props> = p => {
    const { uri, onChange, forceEditMode, readonly, validatedSelection, preview } = p;

    const [editMode, setEditMode] = React.useState<boolean>(!readonly && (uri === "" || forceEditMode));

    const onEditClick = React.useCallback(() => {
        setEditMode(true);
    }, []);

    if (editMode) {
        return (
            <GrowingEntry
                validatedSelection={validatedSelection}
                highlight={true}
                autoFocus={true}
                value={uri}
                onChange={onChange}
            />
        );
    }

    return (
        <UriOverlayEditorStyle>
            <a className="gdg-link-area" href={uri} target="_blank" rel="noopener noreferrer">
                {preview}
            </a>
            {!readonly && (
                <div className="gdg-edit-icon" onClick={onEditClick}>
                    <EditPencil />
                </div>
            )}
            <textarea className="gdg-input" autoFocus={true} />
        </UriOverlayEditorStyle>
    );
};

export default UriOverlayEditor;
