// packages/core/src/internal/data-grid-overlay-editor/data-grid-overlay-editor.tsx
import * as React from "react";
import { createPortal } from "react-dom";

import ClickOutsideContainer from "../click-outside-container/click-outside-container";
import { makeCSSStyle, type Theme, ThemeContext } from "../../common/styles";
import type { GetCellRendererCallback } from "../../cells/cell-types";
import {
    type EditableGridCell,
    type GridCell,
    isEditableGridCell,
    isInnerOnlyCell,
    isObjectEditorCallbackResult,
    type Item,
    type ProvideEditorCallback,
    type ProvideEditorCallbackResult,
    type Rectangle,
    type ValidatedGridCell,
} from "../data-grid/data-grid-types";

import type { CellActivatedEventArgs } from "../data-grid/event-args";
import { DataGridOverlayEditorStyle } from "./data-grid-overlay-editor-style";
import type { OverlayImageEditorProps } from "./private/image-overlay-editor";
import { useStayOnScreen } from "./use-stay-on-screen";

type ImageEditorType = React.ComponentType<OverlayImageEditorProps>;

interface DataGridOverlayEditorProps {
    readonly target: Rectangle;
    readonly cell: Item;
    readonly content: GridCell;
    readonly className?: string;
    readonly id: string;
    readonly initialValue?: string;
    readonly bloom?: readonly [number, number];
    readonly theme: Theme;
    readonly onFinishEditing: (newCell: GridCell | undefined, movement: readonly [-1 | 0 | 1, -1 | 0 | 1]) => void;
    readonly forceEditMode: boolean;
    readonly highlight: boolean;
    readonly portalElementRef?: React.RefObject<HTMLElement>;
    readonly imageEditorOverride?: ImageEditorType;
    readonly getCellRenderer: GetCellRendererCallback;
    readonly markdownDivCreateNode?: (content: string) => DocumentFragment;
    readonly provideEditor?: ProvideEditorCallback<GridCell>;
    readonly activation: CellActivatedEventArgs;
    readonly validateCell?: (
        cell: Item,
        newValue: EditableGridCell,
        prevValue: GridCell
    ) => boolean | ValidatedGridCell;
    readonly isOutsideClick?: (e: MouseEvent | TouchEvent) => boolean;
    readonly customEventTarget?: HTMLElement | Window | Document;
}

const DataGridOverlayEditor: React.FunctionComponent<DataGridOverlayEditorProps> = p => {
    const {
        target,
        content,
        onFinishEditing: onFinishEditingIn,
        forceEditMode,
        initialValue,
        imageEditorOverride,
        markdownDivCreateNode,
        highlight,
        className,
        theme,
        id,
        cell,
        bloom,
        portalElementRef,
        validateCell,
        getCellRenderer,
        provideEditor,
        isOutsideClick,
        customEventTarget,
        activation,
    } = p;

    const [tempValue, setTempValueRaw] = React.useState<GridCell | undefined>(forceEditMode ? content : undefined);
    const lastValueRef = React.useRef(tempValue ?? content);
    lastValueRef.current = tempValue ?? content;

    const [isValid, setIsValid] = React.useState(() => {
        if (validateCell === undefined) return true;
        return !(isEditableGridCell(content) && validateCell?.(cell, content, lastValueRef.current) === false);
    });

    const onFinishEditing = React.useCallback<typeof onFinishEditingIn>(
        (newCell, movement) => {
            onFinishEditingIn(isValid ? newCell : undefined, movement);
        },
        [isValid, onFinishEditingIn]
    );

    const setTempValue = React.useCallback(
        (newVal: GridCell | undefined) => {
            if (validateCell !== undefined && newVal !== undefined && isEditableGridCell(newVal)) {
                const validResult = validateCell(cell, newVal, lastValueRef.current);
                if (validResult === false) {
                    setIsValid(false);
                } else if (typeof validResult === "object") {
                    newVal = validResult;
                    setIsValid(true);
                } else {
                    setIsValid(true);
                }
            }
            setTempValueRaw(newVal);
        },
        [cell, validateCell]
    );

    const finished = React.useRef(false);
    const customMotion = React.useRef<[-1 | 0 | 1, -1 | 0 | 1] | undefined>(undefined);

    const onClickOutside = React.useCallback(() => {
        onFinishEditing(tempValue, [0, 0]);
        finished.current = true;
    }, [tempValue, onFinishEditing]);

    const onEditorFinished = React.useCallback(
        (newValue: GridCell | undefined, movement?: readonly [-1 | 0 | 1, -1 | 0 | 1]) => {
            onFinishEditing(newValue, movement ?? customMotion.current ?? [0, 0]);
            finished.current = true;
        },
        [onFinishEditing]
    );

    const onKeyDown = React.useCallback(
        async (event: React.KeyboardEvent) => {
            let save = false;
            if (event.key === "Escape") {
                event.stopPropagation();
                event.preventDefault();
                customMotion.current = [0, 0];
            } else if (
                event.key === "Enter" &&
                // The shift key is reserved for multi-line editing
                // to allow inserting new lines without closing the editor.
                !event.shiftKey
            ) {
                event.stopPropagation();
                event.preventDefault();
                customMotion.current = [0, 1];
                save = true;
            } else if (event.key === "Tab") {
                event.stopPropagation();
                event.preventDefault();
                customMotion.current = [event.shiftKey ? -1 : 1, 0];
                save = true;
            }

            window.setTimeout(() => {
                if (!finished.current && customMotion.current !== undefined) {
                    onFinishEditing(save ? tempValue : undefined, customMotion.current);
                    finished.current = true;
                }
            }, 0);
        },
        [onFinishEditing, tempValue]
    );

    const targetValue = tempValue ?? content;

    const [editorProvider, useLabel] = React.useMemo((): [ProvideEditorCallbackResult<GridCell>, boolean] | [] => {
        if (isInnerOnlyCell(content)) return [];
        const cellWithLocation = { ...content, location: cell, activation } as GridCell & {
            location: Item;
            activation: CellActivatedEventArgs;
        };
        const external = provideEditor?.(cellWithLocation);
        if (external !== undefined) return [external, false];
        return [getCellRenderer(content)?.provideEditor?.(cellWithLocation), false];
    }, [cell, content, getCellRenderer, provideEditor, activation]);

    const { ref, style: stayOnScreenStyle } = useStayOnScreen();

    let pad = true;
    let editor: React.ReactNode;
    let style = true;
    let styleOverride: React.CSSProperties | undefined;

    if (editorProvider !== undefined) {
        pad = editorProvider.disablePadding !== true;
        style = editorProvider.disableStyling !== true;
        const isObjectEditor = isObjectEditorCallbackResult(editorProvider);
        if (isObjectEditor) {
            styleOverride = editorProvider.styleOverride;
        }
        const CustomEditor = isObjectEditor ? editorProvider.editor : editorProvider;
        editor = (
            <CustomEditor
                portalElementRef={portalElementRef}
                isHighlighted={highlight}
                activation={activation}
                onChange={setTempValue}
                value={targetValue}
                initialValue={initialValue}
                onFinishedEditing={onEditorFinished}
                validatedSelection={isEditableGridCell(targetValue) ? targetValue.selectionRange : undefined}
                forceEditMode={forceEditMode}
                target={target}
                imageEditorOverride={imageEditorOverride}
                markdownDivCreateNode={markdownDivCreateNode}
                isValid={isValid}
                theme={theme}
            />
        );
    }

    styleOverride = { ...styleOverride, ...stayOnScreenStyle };

    // Consider imperatively creating and adding the element to the dom?
    const portalElement = portalElementRef?.current ?? document.getElementById("portal");
    if (portalElement === null) {
        // eslint-disable-next-line no-console
        console.error(
            'Cannot open Data Grid overlay editor, because portal not found. Please, either provide a portalElementRef or add `<div id="portal" />` as the last child of your `<body>`.'
        );
        return null;
    }

    let classWrap = style ? "gdg-style" : "gdg-unstyle";
    if (!isValid) {
        classWrap += " gdg-invalid";
    }

    if (pad) {
        classWrap += " gdg-pad";
    }

    const bloomX = bloom?.[0] ?? 1;
    const bloomY = bloom?.[1] ?? 1;

    return createPortal(
        <ThemeContext.Provider value={theme}>
            <ClickOutsideContainer
                style={makeCSSStyle(theme)}
                className={className}
                onClickOutside={onClickOutside}
                isOutsideClick={isOutsideClick}
                customEventTarget={customEventTarget}>
                <DataGridOverlayEditorStyle
                    ref={ref}
                    id={id}
                    className={classWrap}
                    style={styleOverride}
                    as={useLabel === true ? "label" : undefined}
                    targetX={target.x - bloomX}
                    targetY={target.y - bloomY}
                    targetWidth={target.width + bloomX * 2}
                    targetHeight={target.height + bloomY * 2}>
                    <div className="gdg-clip-region" onKeyDown={onKeyDown}>
                        {editor}
                    </div>
                </DataGridOverlayEditorStyle>
            </ClickOutsideContainer>
        </ThemeContext.Provider>,
        portalElement
    );
};

export default DataGridOverlayEditor;

// packages/vue-core/src/internal/data-grid-overlay-editor/DataGridOverlayEditor.vue
<template>
  <teleport :to="portalElement">
    <div :style="themeStyle" :class="className">
      <ClickOutsideContainer
        :onClickOutside="onClickOutside"
        :isOutsideClick="isOutsideClick"
        :customEventTarget="customEventTarget"
      >
        <DataGridOverlayEditorStyle
          :ref="(el) => setOverlayRef(el as HTMLElement)"
          :id="id"
          :class="classList"
          :style="styleOverride"
          :as="useLabel ? 'label' : undefined"
          :targetX="target.x - bloomX"
          :targetY="target.y - bloomY"
          :targetWidth="target.width + bloomX * 2"
          :targetHeight="target.height + bloomY * 2"
        >
          <div class="gdg-clip-region" @keydown="onKeyDown">
            <component
              :is="editorComponent"
              v-if="editorComponent"
              :portalElementRef="portalElementRef"
              :isHighlighted="highlight"
              :activation="activation"
              :onChange="setTempValue"
              :value="targetValue"
              :initialValue="initialValue"
              :onFinishedEditing="onEditorFinished"
              :validatedSelection="validatedSelection"
              :forceEditMode="forceEditMode"
              :target="target"
              :imageEditorOverride="imageEditorOverride"
              :markdownDivCreateNode="markdownDivCreateNode"
              :isValid="isValid"
              :theme="theme"
            />
          </div>
        </DataGridOverlayEditorStyle>
      </ClickOutsideContainer>
    </div>
  </teleport>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, type Component } from "vue";
import { createApp } from "vue";
import { makeCSSStyle, type Theme } from "../../common/styles";
import type { GetCellRendererCallback } from "../../cells/cell-types";
import {
  type EditableGridCell,
  type GridCell,
  isEditableGridCell,
  isInnerOnlyCell,
  isObjectEditorCallbackResult,
  type Item,
  type ProvideEditorCallback,
  type ProvideEditorCallbackResult,
  type Rectangle,
  type ValidatedGridCell,
} from "../data-grid/data-grid-types";
import type { CellActivatedEventArgs } from "../data-grid/event-args";
import DataGridOverlayEditorStyle from "./DataGridOverlayEditorStyle.vue";
import { useStayOnScreen } from "./use-stay-on-screen";

// Placeholder for ClickOutsideContainer - this would need to be created separately
const ClickOutsideContainer = {
  template: `<div><slot /></div>`,
  props: {
    onClickOutside: Function,
    isOutsideClick: Function,
    customEventTarget: [HTMLElement, Window, Document]
  }
};

interface Props {
  target: Rectangle;
  cell: Item;
  content: GridCell;
  className?: string;
  id: string;
  initialValue?: string;
  bloom?: readonly [number, number];
  theme: Theme;
  onFinishEditing: (newCell: GridCell | undefined, movement: readonly [-1 | 0 | 1, -1 | 0 | 1]) => void;
  forceEditMode: boolean;
  highlight: boolean;
  portalElementRef?: { current: HTMLElement | null };
  imageEditorOverride?: Component;
  getCellRenderer: GetCellRendererCallback;
  markdownDivCreateNode?: (content: string) => DocumentFragment;
  provideEditor?: ProvideEditorCallback<GridCell>;
  activation: CellActivatedEventArgs;
  validateCell?: (
    cell: Item,
    newValue: EditableGridCell,
    prevValue: GridCell
  ) => boolean | ValidatedGridCell;
  isOutsideClick?: (e: MouseEvent | TouchEvent) => boolean;
  customEventTarget?: HTMLElement | Window | Document;
}

const props = defineProps<Props>();

const tempValue = ref<GridCell | undefined>(props.forceEditMode ? props.content : undefined);
const lastValueRef = ref(tempValue.value ?? props.content);
const isValid = ref(true);
if (props.validateCell !== undefined) {
  isValid.value = !(isEditableGridCell(props.content) && props.validateCell?.(props.cell, props.content, lastValueRef.value) === false);
}

const finished = ref(false);
const customMotion = ref<[-1 | 0 | 1, -1 | 0 | 1] | undefined>(undefined);
const { ref: overlayRef, style: stayOnScreenStyle } = useStayOnScreen();
const setOverlayRef = overlayRef;

const themeStyle = computed(() => makeCSSStyle(props.theme));

const classList = computed(() => {
  let classWrap = style.value ? "gdg-style" : "gdg-unstyle";
  if (!isValid.value) {
    classWrap += " gdg-invalid";
  }
  if (pad.value) {
    classWrap += " gdg-pad";
  }
  return classWrap;
});

const validatedSelection = computed(() => {
  const cell = targetValue.value as any;
  return isEditableGridCell(targetValue.value) ? cell.selectionRange : undefined;
});

const targetValue = computed(() => tempValue.value ?? props.content);

const editorProvider = computed(() => {
  if (isInnerOnlyCell(props.content)) return undefined;
  const cellWithLocation = { ...props.content, location: props.cell, activation: props.activation } as GridCell & {
    location: Item;
    activation: CellActivatedEventArgs;
  };
  const external = props.provideEditor?.(cellWithLocation);
  if (external !== undefined) return external;
  return props.getCellRenderer(props.content)?.provideEditor?.(cellWithLocation);
});

const useLabel = computed(() => false);

const pad = computed(() => {
  const provider = editorProvider.value;
  return provider !== undefined && provider.disablePadding !== true;
});

const style = computed(() => {
  const provider = editorProvider.value as any;
  return provider !== undefined && provider.disableStyling !== true;
});

let editorComponent: Component | undefined;
let styleOverride: Record<string, any> = {};

const provider = editorProvider.value;
if (provider !== undefined) {
  const isObjectEditor = isObjectEditorCallbackResult(provider);
  if (isObjectEditor) {
    styleOverride = provider.styleOverride || {};
  }
  editorComponent = isObjectEditor ? provider.editor : provider as Component;
}

styleOverride = { ...styleOverride, ...stayOnScreenStyle };

const portalElement = computed(() => {
  return props.portalElementRef?.current ?? document.getElementById("portal");
});

const bloomX = computed(() => props.bloom?.[0] ?? 1);
const bloomY = computed(() => props.bloom?.[1] ?? 1);

const onClickOutside = () => {
  props.onFinishEditing(tempValue.value, [0, 0]);
  finished.value = true;
};

const onEditorFinished = (newValue: GridCell | undefined, movement?: readonly [-1 | 0 | 1, -1 | 0 | 1]) => {
  props.onFinishEditing(newValue, movement ?? customMotion.value ?? [0, 0]);
  finished.value = true;
};

const onKeyDown = (event: KeyboardEvent) => {
  let save = false;
  if (event.key === "Escape") {
    event.stopPropagation();
    event.preventDefault();
    customMotion.value = [0, 0];
  } else if (
    event.key === "Enter" &&
    !event.shiftKey
  ) {
    event.stopPropagation();
    event.preventDefault();
    customMotion.value = [0, 1];
    save = true;
  } else if (event.key === "Tab") {
    event.stopPropagation();
    event.preventDefault();
    customMotion.value = [event.shiftKey ? -1 : 1, 0];
    save = true;
  }

  window.setTimeout(() => {
    if (!finished.value && customMotion.value !== undefined) {
      props.onFinishEditing(save ? tempValue.value : undefined, customMotion.value);
      finished.value = true;
    }
  }, 0);
};

const setTempValue = (newVal: GridCell | undefined) => {
  if (props.validateCell !== undefined && newVal !== undefined && isEditableGridCell(newVal)) {
    const validResult = props.validateCell(props.cell, newVal, lastValueRef.value);
    if (validResult === false) {
      isValid.value = false;
    } else if (typeof validResult === "object") {
      newVal = validResult;
      isValid.value = true;
    } else {
      isValid.value = true;
    }
  }
  tempValue.value = newVal;
};

watch(() => props.content, (newContent) => {
  lastValueRef.value = tempValue.value ?? newContent;
});
</script>
